server:
  port: 8821

spring:
  application:
    name: cground-order-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.180.87.49:2206/cground_order
    username: cground_order
    password: cground_order12!@
  profiles:
    active: local
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  data:
    redis:
      repositories:
        enabled: false