server:
  port: 8821

spring:
  application:
    name: cground-order-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.111:3306/cground_order
    username: cground_order
    password: cground_order12!@
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
        - file-logging
      prod:
        - console-logging
        - file-logging
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false

  data:
    redis:
      host: 192.168.123.110
      port: 6379
      password: cground12!@